Use single project
Ceecker51/JPEG-Encoder pull request #3
Opened 2019-10-10 17:57 UTC by Ceecker51

This PR does the following:

- move code from assembly "encoder.lib" into "encoder.console"
-

2019-10-10 19:00 UTC, mrvary requested changes
Kannst du `encoder.lib` noch entfernen?

2019-10-10 19:00 UTC, mrvary commented on JPEG-Encoder/encoder.console/Encoder.cs
> +      PixelMap pixelMap = PPMReader.ReadFromPPMFile(filePath, stepX, stepY, isWindows);
Ich würde der Einfachheit halber bei `Picture` bleiben, `pixelMap` ist etwas irreführend, schließlich ist es keine Map sondern nur eine Datenstruktur mit drei Farbkanälen

2019-10-10 19:00 UTC, mrvary commented on JPEG-Encoder/encoder.console/lib/PPMReader.cs
> +      }
Das ist ganz cool so und können wir auch erst mal so lassen. Langfristig schön wäre es eine weniger komplexe Lösung zu finden indem wir einfach Zeilen lesen und dann z.B. auch den struct `dimension` wieder rausschmeißen. Schau mal zur Inspiration die Musterlösung an.

2019-10-11 06:53 UTC, Ceecker51 commented on JPEG-Encoder/encoder.console/Encoder.cs
> +      PixelMap pixelMap = PPMReader.ReadFromPPMFile(filePath, stepX, stepY, isWindows);
Hab ich wieder umgenannt

2019-10-11 06:56 UTC, Ceecker51 commented
> 
> 
> Kannst du `encoder.lib` noch entfernen?

Sollte eigentlich entfernt worden sein.

2019-10-11 07:58 UTC, mrvary commented
> > Kannst du `encoder.lib` noch entfernen?
> 
> Sollte eigentlich entfernt worden sein.

Stimmt!

2019-10-11 07:59 UTC, mrvary approved these changes

2019-10-11 08:56 UTC, merged